services:
  - type: web
    name: fut-gg-extinct-monitor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: DISCORD_WEBHOOK_URL
        sync: false
      - key: MONITORING_CYCLE_INTERVAL
        value: "10"
      - key: ALERT_COOLDOWN_HOURS
        value: "6"
      - key: MAX_PAGES_TO_SCRAPE
        value: "10"
      - key: CARDS_TO_MONITOR_PER_CYCLE
        value: "30"
      - key: SEND_CYCLE_SUMMARIES
        value: "true"