services:
  - type: web
    name: futbin-monitor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
    disk:
      name: futbin-data
      mountPath: /opt/render/project/src
      sizeGB: 1